### ISSUE TITLE
I using use_db, i want to know the secondbase whether better than use_db? 

### ISSUE THREAD

**Issue by ZhangHanDong** [karledurante/secondbase#1]
I using use_db, i want to know the secondbase whether better than use_db?   and the secondebase if support has_many and others relation across database ?

**Comment by karledurante** [comment]
I can't say if Secondbase is "better" then use_db.  However, it appears that Secondbase lets you manage your environment a little easier.  You don't have to do anything different to run your tests or migrations (the standard rake tasks will work).

Secondbase doesn't interfere with ActiveRecord in any way, so you can use any of the relationships or validations provided without worry.

**Comment by ZhangHanDong** [comment]
Thanks for ur reply!!!  i see it!
