### ISSUE TITLE
pending migrations for secondbase does not prevent execution of rake test

### ISSUE THREAD

**Issue by clucas** [karledurante/secondbase#4]
When you have secondbase pending migrations, you can still run rake test without any warning.

**Comment by karledurante** [comment]
This actually turns out to be a bit of a pain.  The ActiveRecord::Migrator class makes some assumptions that prevents me from using it to determine if your second database has any pending migrations...I may have to roll my own solution for that.

**Comment by karledurante** [comment]
Version 0.4.2 fixes this issue!
