### ISSUE TITLE
Use second base for join table

### ISSUE THREAD

**Issue by eavaria** [karledurante/secondbase#5]
is there a way to declare has_and_belongs_to_many to use the second (data)base to store the join table?
I know i can use a join model instead of habtm, but just wondering if you can use something like the :join_table option to change de db...

If it's actually not supported and you figure a way to do it, please tell me and i can work on it and contribute you a bit.

**Comment by karledurante** [comment]
I've not tried to do that...perhaps you'd like to try and let me know if it works ;)

**Comment by karledurante** [comment]
I'm going to close this because you shouldn't be using has_and_belongs_to_many anyway.  has_many :through is the better option.
